### ISSUE TITLE
running rk3288, but display error message

### ISSUE THREAD

**Issue by woojhs** [Planet15/rk3288_rt#2]
Hi

running pllinux on RK3288, but display error message:

Aug 25 02:11:22 beaglebone auth.err getty[416]: can't open '/dev/ttyO0': No such file or directory^M
Aug 25 02:11:32 beaglebone auth.err getty[417]: can't open '/dev/ttyO0': No such file or directory^M
Aug 25 02:11:42 beaglebone auth.err getty[418]: can't open '/dev/ttyO0': No such file or directory^M
Aug 25 02:11:52 beaglebone auth.err getty[419]: can't open '/dev/ttyO0': No such file or directory^M
Aug 25 02:12:02 beaglebone daemon.info init: Id "O0" respawning too fast: disabled for 5 minutes
INIT: Id "O0" respawning too fast: disabled for 5 minutes

what is problem???

**Comment by Planet15** [comment]
Hello 
It will cause problem by inittab in your root file system. 
So, you need to change as below, 
1. vi /etc/inittab
2. Find line 31 , O0:12345:respawn:/sbin/getty -L 115200 ttyO0
3. Need to change , S0:12345:respawn:/sbin/getty -L 115200 ttyS2

You will solve this issue on your board.

BR/Leo
