### ISSUE TITLE
[stress-ng] attr/xattr.h conflicts with new glibc sys/xattr.h 

### ISSUE THREAD

**Issue by Planet15** [Planet15/rk3288_rt#6]
If you want to test stress-test for CPU, I recommend this link as below,
http://kernel.ubuntu.com/~cking/stress-ng/

But you need to install firstly,
You need to compose some produce base on Fedora 22 version, 
1. yum group install "Development Tools"
2. yum install keyutils
3. yum install keyutils-libs*
4. get stress-ng source file.
5. Modify 40 ~ 41lines in stress-xattr.c for stress-ng,
    Remove #include <attr/xattr.h>
    Change #include <sys/xattr.h>
6. Make and enjoy use streess test program!

**Comment by Planet15** [comment]
This issue close :-)

**Comment by woojhs** [comment]
Hi 

I was to test the CPU using stress_ng.
But it was to fail in the yocto package configuration on stress_ng.
It is used to download meta-ivi package for stress_ng. (associated with keyutils)

bellow contents is log

    Loading cache: 100% |########################################################################################################################################################################| ETA:  00:00:00
    Loaded 29 entries from dependency cache.
    ERROR: Please ensure that your setting of VIRTUAL-RUNTIME_init_manager (systemd) matches the entries enabled in DISTRO_FEATURES                                                              | ETA:  --:--:--
    ERROR: Failed to parse recipe: /home/darkofnight/workspace/Planet15/yocto/poky/meta-ivi/meta-ivi/recipes-yocto-ivi/packagegroups/packagegroup-core-boot-genivi.bb

    Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

If you know this problem, say to me.
thx.

**Comment by Planet15** [comment]
Build method for keyutils

1. Copy keyutils from meta-ivi project.
$ cp -rf ./meta-ivi/recipes-support-ivi/keyutils ../../../meta/recipes-devtools/

2. Build keyutils recipe
$ bitbake keyutils
...
NOTE: Preparing RunQueue
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
NOTE: Tasks Summary: Attempted 381 tasks of which 368 didn't need to be rerun and all succeeded.

3. Check binary for keyutils
$ cd tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/keyutils/1.5.8-r1/images


$ tree .
.
├── etc
│   ├── request-key.conf
│   └── request-key.d
└── usr
    ├── bin
    │   └── keyctl
    ├── include
    │   └── keyutils.h
    ├── lib
    │   ├── libkeyutils.a
    │   ├── libkeyutils.so -> libkeyutils.so.1
    │   ├── libkeyutils.so.1 -> libkeyutils.so.1.5
    │   └── libkeyutils.so.1.5
    ├── sbin
    │   ├── key.dns_resolver
    │   └── request-key
    └── share
        ├── keyutils
        │   └── request-key-debug.sh
        └── man
            ├── man1
            │   └── keyctl.1
            ├── man3
            │   ├── keyctl.3
            │   ├── keyctl_assume_authority.3 -> keyctl_instantiate.3
            │   ├── keyctl_chown.3
            │   ├── keyctl_clear.3
            │   ├── keyctl_describe.3
            │   ├── keyctl_describe_alloc.3 -> keyctl_describe.3
            │   ├── keyctl_get_keyring_ID.3
            │   ├── keyctl_get_security.3
            │   ├── keyctl_get_security_alloc.3 -> keyctl_get_security.3
            │   ├── keyctl_instantiate.3
            │   ├── keyctl_instantiate_iov.3 -> keyctl_instantiate.3
            │   ├── keyctl_invalidate.3
            │   ├── keyctl_join_session_keyring.3
            │   ├── keyctl_link.3
            │   ├── keyctl_negate.3 -> keyctl_instantiate.3
            │   ├── keyctl_read.3
            │   ├── keyctl_read_alloc.3 -> keyctl_read.3
            │   ├── keyctl_reject.3 -> keyctl_instantiate.3
            │   ├── keyctl_revoke.3
            │   ├── keyctl_search.3
            │   ├── keyctl_session_to_parent.3
            │   ├── keyctl_setperm.3
            │   ├── keyctl_set_reqkey_keyring.3
            │   ├── keyctl_set_timeout.3
            │   ├── keyctl_unlink.3 -> keyctl_link.3
            │   ├── keyctl_update.3
            │   ├── recursive_key_scan.3
            │   └── recursive_session_key_scan.3 -> recursive_key_scan.3
            ├── man5
            │   └── request-key.conf.5
            └── man8
                ├── key.dns_resolver.8
                └── request-key.8

14 directories, 42 files
